# Run MySQL in a container
version: "3.9"
services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
