# Run MySQL in a container
version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
