#!/usr/bin/env sh

echo "\nRunning postbuild script..."

echo "Creating directory 'app'..."
rm -rf app && mkdir app

echo "Done. Copying 'node_modules' to 'app'..."
cp -r node_modules app

echo "Done. Copying 'build' to 'app'..."
cp -r build app/src

echo "Done. Running 'prisma generate' to update prisma docs..."
npx prisma format
npx prisma generate

echo "Done. Copying 'public' to 'app'..."
cp -r src/public app/src/public

echo "Done. Copying 'package.json' to 'app'..."
cp package.json app

echo "Done. Removing temporary files..."
rm -rf build
