#!/usr/bin/env sh

echo "[WARNING] This will reset the local database. This script should not be run in production!"
cd "$(dirname "$0")/.." || exit 1 # cd to project root

SLEEP_TIME=1
SYNC_SLEEP_TIME=20
MAX_RETRY=5
MAX_SYNC_RETRY=5

while true; do
    read -p "Are you sure you want to continue? [y/N]: " yn
    case $yn in
    [Yy]*)
        echo "\nResetting local database..."

        yarn docker:reset
        sleep $SLEEP_TIME

        cd docker || exit 1
        MYSQL_STARTED=0

        while [ $MYSQL_STARTED -eq 0 ]; do

            if [ $MAX_RETRY -eq 0 ]; then
                echo "Failed to start MySQL container. Exiting..."
                exit 1
            fi

            MAX_RETRY=$((MAX_RETRY - 1))
            echo "Waiting for MySQL to start. Retries left: $MAX_RETRY"

            sleep $SLEEP_TIME
            docker-compose exec mysql mysql -u root -psecret -e "SELECT 1" >/dev/null 2>&1
            MYSQL_STARTED=$?

        done

        cd .. || exit 1
        # https://stackoverflow.com/a/46597567/17268969
        # try
        (
            # this flag will make to exit from current subshell on any error
            # inside it (all functions run inside will also break on any error)
            set -e
            yarn db:sync
        )
        # catch
        errorCode=$?
        while [ $errorCode -ne 0 ]; do
            echo "\nDb sync error. This is probably because docker is still starting up."
            echo "Retries left: $MAX_SYNC_RETRY. Retrying in $SYNC_SLEEP_TIME seconds..."
            sleep $SYNC_SLEEP_TIME

            MAX_SYNC_RETRY=$((MAX_SYNC_RETRY - 1))
            if [ $MAX_SYNC_RETRY -eq 0 ]; then
                echo "Failed to sync database. Exiting..."
                exit 1
            fi

            (
                set -e
                yarn db:sync
            )
            errorCode=$?
        done

        echo "Local database reset complete."
        break
        ;;
    [Nn]*)
        echo "Exit without resetting local database."
        exit
        ;;
    *) echo "Please answer yes or no." ;;
    esac
done
