#!/usr/bin/env sh

cd "$(dirname "$0")/.." || exit 1 # cd to project root

echo "Cleaning up workspace..."

echo "Removing node_modules..."
rm -rf node_modules

echo "Removing temp files..."
rm -rf build dist coverage app docs log base64*

echo "Installing dependencies..."
yarn install

while true; do
    read -p "Do you want to reset the database? [y/N]: " yn
    case $yn in
    [Yy]*)
        echo "Resetting local database..."
        yarn db:local:reset
        break
        ;;
    [Nn]*)
        echo "Skipping database reset. Generating prisma client..."
        yarn db:gen:schema
        break
        ;;
    *)
        echo "Skipping database reset..."
        break
        ;;
    esac
done
