export enum OrderStatus {
    PENDING_PAYMENT = "PENDING_PAYMENT",
    PAYMENT_FAILED = "PAYMENT_FAILED",
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
    PROCESSING = "PROCESSING",
    PENDING_SHIPMENT = "PENDING_SHIPMENT",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    CANCELLED = "CANCELLED"
}
